### ISSUE TITLE
Doesn't work correctly, zooms to single pixel

### ISSUE THREAD

**Issue by IshanJ25** [tryptech/obs-zoom-and-follow#45] opened 2022-05-23 07:50 UTC
I have only tested on windows 11:

last commit that works correctly is `68e1aef99cb2d55a60324e1ea9d48f92815f8949`

after that it zooms to a single pixel at top left corner

**Comment by IshanJ25** [comment] 2022-05-23 07:51
maybe try to restore the previous version with new fixes?

**Comment by JotaRata** [comment] 2022-06-12 22:50
This is still happening

**Comment by Mamdouh-Abdo** [comment] 2022-07-17 00:44
me too

**Comment by davidvkimball** [comment] 2022-07-18 21:48
Same is happening to me. Windows 10.

**Comment by tryptech** [comment] 2022-07-19 04:04
Please try the most recent commit, there is mixed reports of it working and not exhibiting this behavior.

**Comment by tryptech** [comment] 2022-07-19 04:04
Duplicate of #40

**Closed by tryptech** 2022-07-19 04:04 UTC
