### ISSUE TITLE
not working with wide screen

### ISSUE THREAD

**Issue by Username69992872** [tryptech/obs-zoom-and-follow#117] opened 2023-06-07 17:57 UTC
I got a 5120x1440 Widescreen Monitor. I want it to work with a Window which is 2560x1440 on the right half of the screen. 
Whatever I set, it just does not work. Expecially it somehow resets the Source Crop Filter to width 0 height 0 always. No Idea why.

**Comment by Username69992872** [comment] 2023-06-11 12:09
hello? anyone there ?

**Comment by tryptech** [comment] 2023-09-12 13:52
Duplicate of #90. Closing.

**Closed by tryptech** 2023-09-12 13:52 UTC
