### ISSUE TITLE
NSWindow drag regions should only be invalidated on the Main Thread

### ISSUE THREAD

**Issue by super-ibby** [tryptech/obs-zoom-and-follow#75] opened 2022-10-15 20:45 UTC
Hi,

The script fails to zoom in with the following error:

```
objc.error: NSInternalInconsistencyException - NSWindow drag regions should only be invalidated on the Main Thread!
```

Full script log (using **v2022.09.22**) with source transform set to **Stretch to bounds**:

```
[zoom_and_follow_mouse.py] Source update
[zoom_and_follow_mouse.py] No sources, likely OBS startup.
[zoom_and_follow_mouse.py] Source Name: Firefox
[zoom_and_follow_mouse.py] Updating Source List
[zoom_and_follow_mouse.py] System: Darwin
[zoom_and_follow_mouse.py] browser frame | <Swig Object of type 'obs_source_t *' at 0x1292c3b10>
[zoom_and_follow_mouse.py] Firefox | <Swig Object of type 'obs_source_t *' at 0x1292c3a20>
[zoom_and_follow_mouse.py] logo | <Swig Object of type 'obs_source_t *' at 0x1292c39f0>
[zoom_and_follow_mouse.py] cam frame | <Swig Object of type 'obs_source_t *' at 0x1292c33c0>
[zoom_and_follow_mouse.py] webcam | <Swig Object of type 'obs_source_t *' at 0x1292c3960>
[zoom_and_follow_mouse.py] canon m50 | <Swig Object of type 'obs_source_t *' at 0x1293280f0>
[zoom_and_follow_mouse.py] PowerPoint | <Swig Object of type 'obs_source_t *' at 0x129328180>
[zoom_and_follow_mouse.py] white | <Swig Object of type 'obs_source_t *' at 0x129328150>
[zoom_and_follow_mouse.py] New source: True
[zoom_and_follow_mouse.py] Updating Monitor List
[zoom_and_follow_mouse.py] Monitor override list updated
[zoom_and_follow_mouse.py] window_capture
[zoom_and_follow_mouse.py] Source Type: window_capture
[zoom_and_follow_mouse.py] Proceeding to resize
[zoom_and_follow_mouse.py] Updating stored dimensions to match current dimensions
[zoom_and_follow_mouse.py] /usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/Current/lib/python3.10/site-packages/pywinctl/_pywinctl_macos.py:427: UninitializedDeallocWarning: leaking an uninitialized object of type NSWindow
[zoom_and_follow_mouse.py]   w = AppKit.NSWindow.alloc().initWithContentRect_styleMask_backing_defer_(frame, mask, AppKit.NSBackingStoreBuffered, False)
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "/Users/ibby/Documents/OBS/scripts/obs-zoom-and-follow-master/zoom_and_follow_mouse.py", line 820, in toggle_zoom
[zoom_and_follow_mouse.py]     zoom.update_source_size()
[zoom_and_follow_mouse.py]   File "/Users/ibby/Documents/OBS/scripts/obs-zoom-and-follow-master/zoom_and_follow_mouse.py", line 283, in update_source_size
[zoom_and_follow_mouse.py]     self.update_window_dim(self.window)
[zoom_and_follow_mouse.py]   File "/Users/ibby/Documents/OBS/scripts/obs-zoom-and-follow-master/zoom_and_follow_mouse.py", line 69, in update_window_dim
[zoom_and_follow_mouse.py]     window_dim = window.getClientFrame()
[zoom_and_follow_mouse.py]   File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/Current/lib/python3.10/site-packages/pywinctl/_pywinctl_macos.py", line 490, in getClientFrame
[zoom_and_follow_mouse.py]     titleHeight, borderWidth = _getBorderSizes()
[zoom_and_follow_mouse.py]   File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/Current/lib/python3.10/site-packages/pywinctl/_pywinctl_macos.py", line 427, in _getBorderSizes
[zoom_and_follow_mouse.py]     w = AppKit.NSWindow.alloc().initWithContentRect_styleMask_backing_defer_(frame, mask, AppKit.NSBackingStoreBuffered, False)
[zoom_and_follow_mouse.py] objc.error: NSInternalInconsistencyException - NSWindow drag regions should only be invalidated on the Main Thread!
[zoom_and_follow_mouse.py] Tracking: False
```

And after setting the transform to **Scale to inner bounds**:

```
[zoom_and_follow_mouse.py] window_capture
[zoom_and_follow_mouse.py] Source Type: window_capture
[zoom_and_follow_mouse.py] Proceeding to resize
[zoom_and_follow_mouse.py] Updating stored dimensions to match current dimensions
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "/Users/ibby/Documents/OBS/scripts/obs-zoom-and-follow-master/zoom_and_follow_mouse.py", line 820, in toggle_zoom
[zoom_and_follow_mouse.py]     zoom.update_source_size()
[zoom_and_follow_mouse.py]   File "/Users/ibby/Documents/OBS/scripts/obs-zoom-and-follow-master/zoom_and_follow_mouse.py", line 283, in update_source_size
[zoom_and_follow_mouse.py]     self.update_window_dim(self.window)
[zoom_and_follow_mouse.py]   File "/Users/ibby/Documents/OBS/scripts/obs-zoom-and-follow-master/zoom_and_follow_mouse.py", line 69, in update_window_dim
[zoom_and_follow_mouse.py]     window_dim = window.getClientFrame()
[zoom_and_follow_mouse.py]   File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/Current/lib/python3.10/site-packages/pywinctl/_pywinctl_macos.py", line 490, in getClientFrame
[zoom_and_follow_mouse.py]     titleHeight, borderWidth = _getBorderSizes()
[zoom_and_follow_mouse.py]   File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/Current/lib/python3.10/site-packages/pywinctl/_pywinctl_macos.py", line 427, in _getBorderSizes
[zoom_and_follow_mouse.py]     w = AppKit.NSWindow.alloc().initWithContentRect_styleMask_backing_defer_(frame, mask, AppKit.NSBackingStoreBuffered, False)
[zoom_and_follow_mouse.py] objc.error: NSInternalInconsistencyException - NSWindow drag regions should only be invalidated on the Main Thread!
[zoom_and_follow_mouse.py] Tracking: True
```

I am on **MacOS 12.6,** and using **OBS 28.0.3**.

Thanks!

**Comment by tryptech** [comment] 2022-10-21 21:37
The issue appears to be an issue with the getClientFrame function in PyWinCtl. Initial searches suggest that this is an issue that comes up on MacOS, though I haven't read into it deep enough to figure out specifics. It might be more to add an issue there; please feel free to reference this issue and [this one](https://github.com/matplotlib/matplotlib/issues/14304/) as they seem to have a similar enough, if not the same, root cause

**Comment by super-ibby** [comment] 2022-10-23 22:43
Thank you. I've raised an issue on the `pywinctl` repo, [here](https://github.com/Kalmat/PyWinCtl/issues/26).

**Comment by tryptech** [comment] 2022-10-25 05:31
@Kalmat Once again, thank you for the clarification and ongoing support. I wasn't aware of the specifics and challenges that MacOS faces with using AppleScript this way. 

So as it currently stands, a refactor is in order for proper Mac support for any sources other than display capture.

@super-ibby I would love to fix this issue proper for you and other Mac users, but at the moment I don't think I could. Testing and debugging would be difficult as I don't have any macOS devices. Current support is predominantly due to pull request #32 but that's about the extent of it.

**Comment by super-ibby** [comment] 2022-10-26 01:08
Thank you, @tryptech and @Kalmat !

@tryptech , I will experiment and report back when I have a chance -- usually the weekends.

**Comment by super-ibby** [comment] 2023-02-02 03:43
Hi @tryptech , @Kalmat ,

I have finally gotten around to looking at this. It looks like the issue is with `pywinctl` as the following seems to always open in a background thread:

```python
AppKit.NSWindow.alloc().initWithContentRect_styleMask_backing_defer_(frame, mask, AppKit.NSBackingStoreBuffered, False)
```

I confirmed this by replicating the AppKit call using AppleScript in ScriptEditor:

<img width="700" alt="Screenshot 2023-02-01 at 10 36 04 PM" src="https://user-images.githubusercontent.com/112219012/216225624-a5ccf3b5-ad2b-4be7-88cd-f6dcc4b77470.png">

The good news is that I've managed to write some AppleScript that will force the dummy window to be created on the main thread:

```AppleScript
use framework "Foundation"

on run
	set theResult to {0, 0}
	tell (current application)
		my performSelectorOnMainThread:"getTitleBarHeightAndBorderWidth" withObject:0 waitUntilDone:true
	end tell
	--log theResult
	return theResult
end run

on getTitleBarHeightAndBorderWidth()
	
	set |⌘| to current application
	
	set theFrameWidth to 250
	
	tell (|⌘|'s NSWindow's alloc()'s ¬
		initWithContentRect:{{400, 800}, {theFrameWidth, 100}} ¬
			styleMask:(|⌘|'s NSTitledWindowMask) ¬
			backing:(|⌘|'s NSBackingStoreBuffered) ¬
			defer:true)
		set theWindow to it
		set its releasedWhenClosed to true
		set its excludedFromWindowsMenu to true
	end tell
	
	set theFrame to theWindow's frame()
	
	set theTitleHeight to theWindow's titlebarHeight() as integer
	--log theTitleHeight
	
	set theContentRect to theWindow's contentRectForFrameRect:theFrame
	--log theContentRect
	
	set x1 to (|⌘|'s NSMinX(theContentRect)) as integer
	set x2 to (|⌘|'s NSMaxX(theContentRect)) as integer
	--log x1
	--log x2
	
	set theBorderWidth to (theFrameWidth - (x2 - x1)) as integer
	--log theBorderWidth
	
	set my theResult to {theTitleHeight, theBorderWidth}
	--log my theResult
	
	theWindow's |close|()
	return
end getTitleBarHeightAndBorderWidth
```

I will create a PR in the `pywinctl` repo shortly.

**Comment by tryptech** [comment] 2023-02-03 23:09
I took a look through that PR, very good work. I'll update the minreq of PyWinCtl soon.
In a few weeks I intend to pick up an M2 Mac Mini and start doing Mac testing.

**Comment by tryptech** [comment] 2023-02-20 07:39
I'm going to continue working on all Mac related issues in https://github.com/tryptech/obs-zoom-and-follow/issues/97 so I will close this for now. Please put any notes, issues, observations, etc. in that issue.

**Closed by tryptech** 2023-02-20 07:39 UTC
Labels: bug

**Comment by Kalmat** [comment] 2023-02-20 09:00
Nice! Count on it! I'm finishing a new version which includes a number of improvements, including the one from @super-ibby to allow threads invoking getClientFrame() method. I will notify you as soon as it is ready so you can use it.
