### ISSUE TITLE
Error any time attempting zoom - using two monitors maybe?

### ISSUE THREAD

**Issue by IAmTerrific** [tryptech/obs-zoom-and-follow#34] opened 2022-04-06 05:55 UTC
Traceback (most recent call last):
line 370, in toggle_zoom
zoom.update_source_size()
line 64, in update_source_size
data = loads(data)['monitor']
KeyError: 'monitor'

**Comment by IAmTerrific** [comment] 2022-04-06 06:03
Solved: OBS needed to be restarted after installing script.

**Comment by IAmTerrific** [comment] 2022-04-06 06:14
Restarting OBS fixes the error for a moment. Plugin is straight up broken, and permanently breaks and Desktop Capture source I use it on by permanently setting it to zoom into the top left pixel whenever leaving zoom mode. Until it eventually starts giving the above error again and breaks entirely.

**Comment by tryptech** [comment] 2022-04-06 20:24
I need more information than that
OS, python version, OBS version, monitor sizes and relative positioning, anything.

I'm running a 3840x1600 and a 2560x1440 monitor right next to each other and I have no issues, so I need something to go off of.

**Comment by clarkio** [comment] 2022-04-07 21:31
I'm experiencing similar results with the script not working. Here is some more information on the context in which the issue shows up:

I'm on Windows 10, OBS 27.2.4 (64 bit), main monitor used for zoom and follow is 2560x1440, monitor capture properties is set to the following:
![image](https://user-images.githubusercontent.com/6265396/162321424-79711992-dfe2-4a3a-ba98-54d0ddb9740c.png)

Script settings are set to the following:
![image](https://user-images.githubusercontent.com/6265396/162322270-6406f488-963c-43e9-9818-52ca7d01fbde.png)

I'm not sure if that information helps but I hope so. I'm happy to share more that might help as well. Thanks for putting this together and I hope to get it working to use.

**Comment by clarkio** [comment] 2022-04-07 21:33
Also here's my Python packages with versions:
![image](https://user-images.githubusercontent.com/6265396/162323610-db2ab335-516d-4faf-8b95-5740601901eb.png)

**Comment by tryptech** [comment] 2022-04-07 22:05
Could you record a short clip of what happens when you zoom in and out from OBS?

**Comment by clarkio** [comment] 2022-04-07 22:31
Sure I could try but it doesn't zoom in or out so I wouldn't have much to show in that regard. I press the keyboard shortcut I assigned to it and then the script log pops up with the error message.

**Comment by IAmTerrific** [comment] 2022-04-07 23:11
[2022-04-07 16-03-12.zip](https://github.com/tryptech/obs-zoom-and-follow/files/8447340/2022-04-07.16-03-12.zip)
Okay i got the broken zooming to run without producing the error, i just made sure to restart OBS after loading the script and assigning the source, not sure if that is what avoided it though, but I spammed it a whole bunch this time and so far no error message.

The source starts at 1920x1080 (scaled down from 2440x1440), centered, set to scale to bounds, bounds set to 1920x1080.

The first zoom works, but then disabling zoom sets the source transform to .75 x .75 as indicated in the edit transform box.

**Comment by IAmTerrific** [comment] 2022-04-07 23:15
Additional requested info:
![Capture](https://user-images.githubusercontent.com/78352505/162334234-15db07a1-1995-4965-bb53-25099914d436.PNG)

Windows 10 (64 bit)

OBS version 26.2.4 (64 bit)

Primary Monitor: 2440x1440 @ 0,0
Secondary Monitor: 1920x1080 @ -1920 , 218

**Comment by clarkio** [comment] 2022-04-07 23:21
@IAmTerrific oh I wanna make sure I understand how you resolved it. You loaded the script, set the source up and then restarted OBS?

**Comment by clarkio** [comment] 2022-04-07 23:47
I kinda get it to work with that but it zooms in a huge amount even with Zoom Window Height and Width set to 1280 and 720 respectively.

**Comment by clarkio** [comment] 2022-04-08 00:12
https://user-images.githubusercontent.com/6265396/162338991-5124aa88-c40f-49f3-aa5a-91eb0ba0e470.mp4

**Comment by clarkio** [comment] 2022-04-08 00:34
@IAmTerrific I moved to this previous version of the script and dependencies. This got it working consistently for me. https://github.com/tryptech/obs-zoom-and-follow/tree/68e1aef99cb2d55a60324e1ea9d48f92815f8949

@tryptech having switched to the previous script version with the other dependencies I'm thinking the issue is around the use of PyWinCtl. I'd be happy to try and debug this further but I'm not familiar with how I can do that in an efficient way with the dependency on loading the script into OBS

**Comment by tryptech** [comment] 2022-04-08 02:20
> Also I modified the script to print out the contents of what `loads(data)` returns and can see it's missing the key `monitor` which is causing the error. Here's an example: `{'capture_cursor': True, 'method': 1}`

So when you load the script up, do you already have any existing window/desktop sources? If you create them after loading the script I think that it doesn't load up the sources properly so I might have to revisit that for a performant way of updating that list.

**Comment by IAmTerrific** [comment] 2022-04-08 02:26
I created the desktop source first. Loaded script, then assigned the source
in obs. The same process the first attempts produced the error, the last
time all i did differently was restart OBS before attempting zoom

**Comment by clarkio** [comment] 2022-04-08 02:49
> > Also I modified the script to print out the contents of what `loads(data)` returns and can see it's missing the key `monitor` which is causing the error. Here's an example: `{'capture_cursor': True, 'method': 1}`
> 
> 
> 
> So when you load the script up, do you already have any existing window/desktop sources? If you create them after loading the script I think that it doesn't load up the sources properly so I might have to revisit that for a performant way of updating that list.

I already have an existing window/desktop source

**Comment by IAmTerrific** [comment] 2022-04-08 05:51
@clarkio thank you that fixed it, working wonderfull! 👍

**Comment by tryptech** [comment] 2022-04-08 07:03
> Also I modified the script to print out the contents of what `loads(data)` returns and can see it's missing the key `monitor` which is causing the error. Here's an example: `{'capture_cursor': True, 'method': 1}`

Very odd, I just did a print of loads(data) before doing anything else and I got:
`{'capture_cursor': True, 'method': 0, 'monitor': 0, 'monitor_wgc': 0}`

It makes sense that the error is happening from a lack of monitor key, but I'm not experiencing the issue myself.
I'm on Windows 11, but it's almost Windows 10 under the hood so I'm not sure what's happening there. I'll try to see if it's getting skipped somehow in PyWinCtl

**Comment by OmaGamer** [comment] 2022-04-18 11:47
I'm having the same issue where is the loads Json file ?

**Comment by tryptech** [comment] 2022-04-30 03:43
I believe I've corrected the issue as of https://github.com/tryptech/obs-zoom-and-follow/commit/65d92ff2cf29f6ecc61d49dc58a272c259cf30c7

Can you test and see if the issue persists?

**Comment by clarkio** [comment] 2022-05-01 00:32
Hmm updated my local script with your latest changes and I'm still getting an issue when activating it

https://user-images.githubusercontent.com/6265396/166126343-cb9e0337-2f06-44a5-8607-1ad129df1806.mp4

Here are my script settings too:
![image](https://user-images.githubusercontent.com/6265396/166126356-3bf6265a-87c0-4c25-87ac-288b21905e6b.png)


The script logs show the following details:
```
[zoom_and_follow_mouse.py] Key 'monitor' does not exist in data
[zoom_and_follow_mouse.py] {}
[zoom_and_follow_mouse.py] Key 'monitor' does not exist in data
[zoom_and_follow_mouse.py] {}
[zoom_and_follow_mouse.py] Key 'monitor' does not exist in data
[zoom_and_follow_mouse.py] {}
```

Does my version of Windows matter? I'm on Windows 10 Version 21H2 for x64 using OBS 27.2.4 (64 bit). Python is version 3.6.8 and pywinctl is 0.0.32.

I made sure to adjust the transform on my desktop capture source to be center and stretch to inner bounds. Here are the settings for that:
![image](https://user-images.githubusercontent.com/6265396/166126815-b22a3d2d-c5ab-4994-a1db-1906f7560d79.png)

**Comment by tryptech** [comment] 2022-05-02 00:31
Hm, I wonder if there's a difference in the data structure for windows 11. Seems like an unreasonable assumption, but I might have to look into that

**Comment by tryptech** [comment] 2022-05-03 06:17
@clarkio Here's a version of the plugin that should output all of the display source monitor data in the script log.
Would you mind running it and giving me the full output?


[debug_output.zip](https://github.com/tryptech/obs-zoom-and-follow/files/8608534/debug_output.zip)

**Comment by clarkio** [comment] 2022-05-03 16:58
Tried and here are the results:

```
[zoom_and_follow_mouse_debug.py] Key 'monitor' does not exist in data
[zoom_and_follow_mouse_debug.py] Source name: Display Capture
[zoom_and_follow_mouse_debug.py] Source: 
[zoom_and_follow_mouse_debug.py] <Swig Object of type 'obs_source_t *' at 0x...>
[zoom_and_follow_mouse_debug.py] Source Settings: 
[zoom_and_follow_mouse_debug.py] <Swig Object of type 'obs_data_t *' at 0x...>
[zoom_and_follow_mouse_debug.py] OBS Data: 
[zoom_and_follow_mouse_debug.py] {}
[zoom_and_follow_mouse_debug.py] {}
```

**Comment by tryptech** [comment] 2022-05-03 17:25
Oddly enough, the data from the OBS source is completely blank.

I'm normally expecting an output like this:
```
[zoom_and_follow_mouse.py] Source name: Display Capture
[zoom_and_follow_mouse.py] Source: 
[zoom_and_follow_mouse.py] <Swig Object of type 'obs_source_t *' at 0x000001F83679AFC0>
[zoom_and_follow_mouse.py] Source Settings: 
[zoom_and_follow_mouse.py] <Swig Object of type 'obs_data_t *' at 0x000001F8558F3210>
[zoom_and_follow_mouse.py] OBS Data: 
[zoom_and_follow_mouse.py] {"capture_cursor":true,"method":2,"monitor":0,"monitor_wgc":0}
```

Your display capture source properties look like this?
![image](https://user-images.githubusercontent.com/654389/166506227-dc1ef7d5-8fcb-47e1-8021-04ad128abc77.png)

**Comment by clarkio** [comment] 2022-05-03 17:38
Tried that and got the same visual results but different log results:

```
[zoom_and_follow_mouse_debug.py] Key 'monitor' does not exist in data
[zoom_and_follow_mouse_debug.py] Source name: Display Capture
[zoom_and_follow_mouse_debug.py] Source: 
[zoom_and_follow_mouse_debug.py] <Swig Object of type 'obs_source_t *' at 0x...>
[zoom_and_follow_mouse_debug.py] Source Settings: 
[zoom_and_follow_mouse_debug.py] <Swig Object of type 'obs_data_t *' at 0x...>
[zoom_and_follow_mouse_debug.py] OBS Data: 
[zoom_and_follow_mouse_debug.py] {"method":2}
[zoom_and_follow_mouse_debug.py] {'method': 2}

**Comment by tryptech** [comment] 2022-05-03 18:22
Well at least there's data now, some progress. I ran through the different capture methods on my end as well, but I'm getting back the exact same data, with only one value change.

```[zoom_and_follow_mouse.py] Source name: Display Capture
[zoom_and_follow_mouse.py] Source: 
[zoom_and_follow_mouse.py] <Swig Object of type 'obs_source_t *' at 0x000001F83679AFC0>
[zoom_and_follow_mouse.py] Source Settings: 
[zoom_and_follow_mouse.py] <Swig Object of type 'obs_data_t *' at 0x000001F8558F3210>
[zoom_and_follow_mouse.py] OBS Data: 
[zoom_and_follow_mouse.py] {"capture_cursor":true,"method":2,"monitor":0,"monitor_wgc":0}
[zoom_and_follow_mouse.py] Source name: Display Capture
[zoom_and_follow_mouse.py] Source: 
[zoom_and_follow_mouse.py] <Swig Object of type 'obs_source_t *' at 0x000001F83679AFC0>
[zoom_and_follow_mouse.py] Source Settings: 
[zoom_and_follow_mouse.py] <Swig Object of type 'obs_data_t *' at 0x000001F8558F3120>
[zoom_and_follow_mouse.py] OBS Data: 
[zoom_and_follow_mouse.py] {"capture_cursor":true,"method":1,"monitor":0,"monitor_wgc":0}
[zoom_and_follow_mouse.py] Source name: Display Capture
[zoom_and_follow_mouse.py] Source: 
[zoom_and_follow_mouse.py] <Swig Object of type 'obs_source_t *' at 0x000001F83679AFC0>
[zoom_and_follow_mouse.py] Source Settings: 
[zoom_and_follow_mouse.py] <Swig Object of type 'obs_data_t *' at 0x000001F8558F3120>
[zoom_and_follow_mouse.py] OBS Data: 
[zoom_and_follow_mouse.py] {"capture_cursor":true,"method":0,"monitor":0,"monitor_wgc":0}
```


At least on my end, I know that my monitors are being captured with this part of OBS: https://github.com/obsproject/obs-studio/blob/b94e960d253e5889a859f737120340d2da242bc2/plugins/win-capture/duplicator-monitor-capture.c
It's the only place **monitor_wgc** is ever mentioned. Maybe it's because my monitor/system is hdr capable that I get these results specifically.

**Comment by clarkio** [comment] 2022-05-03 19:06
Possibly, but I'm still curious as to what the difference is between the libraries you use for this purpose in your latest script vs. the libraries used in the previous version here: https://github.com/tryptech/obs-zoom-and-follow/tree/68e1aef99cb2d55a60324e1ea9d48f92815f8949

If OBS can recognize my monitor using those libraries I'm wondering why not with this latest one? Is it doing something differently?

**Comment by tryptech** [comment] 2022-05-03 20:11
I changed dependencies so I could expand the zoom function to window capture as well. The issue though doesn't seem to be with the dependencies necessarily. 

In the old version, it iterated through the list of monitors and checked if its name matched the selected monitor. Now, I'm getting the monitor info that OBS has from the selected source, and using that to key the list of monitors the system reports, match happens based on the ID between the two. I prefer this way in case there are other monitor devices in the system that potentially screw up ordering, and in the case that some window manager in Linux behaves a bit differently.

**Comment by clarkio** [comment] 2022-05-04 00:39
Ah I understand. That makes sense and seems like a safer way to go about this. I'm a bit stumped as to why OBS isn't reporting the monitor details for this. 🤷‍♂️ I'll keep trying to dig for an answer more over time and see if anything comes up

**Comment by tryptech** [comment] 2022-07-19 03:13
It's been a few months, someone did submit a PR that fixed a bug for single monitor users. I don't think it affects your case in particular, but if you discover anything, let me know and I'll reopen the issue.

**Closed by tryptech** 2022-07-19 03:13 UTC
