### ISSUE TITLE
Unable to Launch Script

### ISSUE THREAD

**Issue by micky3knuckles** [tryptech/obs-zoom-and-follow#39] opened 2022-05-07 02:06 UTC
I am getting the following when I try to load the script into OBS

[zoom_and_follow_mouse.py]   File "D:/BACKUP-2020/Projects/Twitch/obs-zoom-and-follow-master\zoom_and_follow_mouse.py", line 2, in <module>
[zoom_and_follow_mouse.py]     import pywinctl as pwc # version >=0.0.30
[zoom_and_follow_mouse.py] ModuleNotFoundError: No module named 'pywinctl'

I have run the pip to install this as well as installed the newest .whl file and I get the same error whenever I choose the scrpt.

**Comment by raspberyl08** [comment] 2022-05-07 09:15
I've the same issue. It says "ModuleNotFoundError: No module named 'pywinctl'"

**Comment by gabe-over** [comment] 2022-05-07 10:02
Looks like you didn't install pywinctl module.

> pip install pywinctl

**Comment by raspberyl08** [comment] 2022-05-07 14:05
> Looks like you didn't install pywinctl module.
> 
> > pip install pywinctl

Ah! correct. It is my first time using github. Did not know about "Dependencies" section.

**Comment by micky3knuckles** [comment] 2022-05-07 18:38
I did install it, which I referenced above.  Here is what I get now when I type in the command:

C:\Users\myuck>pip install pywinctl
Requirement already satisfied: pywinctl in c:\users\myuck\appdata\local\programs\python\python310\lib\site-packages (0.0.36)
Requirement already satisfied: PyRect~=0.1 in c:\users\myuck\appdata\local\programs\python\python310\lib\site-packages (from pywinctl) (0.2.0)
Requirement already satisfied: pywin32>=302 in c:\users\myuck\appdata\local\programs\python\python310\lib\site-packages (from pywinctl) (304)

I also tried to install the whl file seperately, which was successful

**Comment by TheRealSlander** [comment] 2022-05-11 00:53
I have the exact same problem as OP, but I'm using the **snap** version of OBS under Manjaro linux.
When I try to add the script to OBS, I have the following message:
```
error: [Python: zoom_and_follow_mouse.py] Traceback (most recent call last):
error: [Python: zoom_and_follow_mouse.py]   File "/home/slander/OBS Streaming/Scripts/zoom_and_follow_mouse.py", line 2, in <module>
error: [Python: zoom_and_follow_mouse.py]     import pywinctl as pwc # version >=0.0.30
error: [Python: zoom_and_follow_mouse.py] ModuleNotFoundError: No module named 'pywinctl'
```
I have installed pywinctl using the following command (also tried without the sudo):
```
sudo python -m pip pywinctl
```
I tried to get an answer on stackoverflow, but they directed me here.
The stackoverflow question is here: https://stackoverflow.com/questions/71954531/obs-python-script-cannot-find-module-error-obs-snap-linux-edition
I link the question as there is more infos on the environment there.

**Comment by CatxOfficial** [comment] 2022-05-18 03:12
> I've the same issue. It says "ModuleNotFoundError: No module named 'pywinctl'"

I have the same issue, I tried fixing it using the pip install method but now it just says
`import win32api
[zoom_and_follow_mouse.py] ModuleNotFoundError: No module named 'win32api'`

**Comment by tryptech** [comment] 2022-07-19 03:28
@micky3knuckles Could you make sure that the Python Settings tab is pointing to an installation of Python 3.6.8 or lower? And make sure that you install PyWinCtl under that version of Python. It is possible to install PyWinCtl under a different version of Python, thus OBS will not see it.

@TheRealSlander I'm not sure if your issue is the same as the previous, but I would make sure OBS is using the right version of Python. I'm not sure if it's using a self-contained version of python but it definitely isn't using the 3.10 version that has PyWinCtl installed.

**Comment by tryptech** [comment] 2022-07-19 04:11
If the issue isn't resolved by making sure your Python versions are correct, please let me know and I will reopen the issue.

**Closed by tryptech** 2022-07-19 04:11 UTC
Labels: question

**Comment by Scrxtchy** [comment] 2022-08-05 16:17
I had some issues in the past when helping people setup this script with python36, and it always came from pywinctl not being able to load the win32api module. However with version 28 of obs allowing us to use python3.10 (https://github.com/obsproject/obs-studio/commit/ab21c7e5b098170ca468edc490c2d6705c65e021) this package problem hasn't been an issue with new installs
